version: "3"
services: 
  postgres_app:
    container_name: postgres_app
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=mission
      - POSTGRES_DB=mission_db
    volumes:
      - ./build/postgres-data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d