{
 "title": "Echo Framework Processes",
 "description": "Dashboard for applications that use https://github.com/globocom/echo-prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mission_observability_requests_total, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mission_observability_requests_total, instance)"
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": "label_values(mission_observability_requests_total, handler)"
   }
  ]
 },
 "panels": [
  { "title": "database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection open",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_sql_stats_connections_open", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Maximum number of open connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_sql_stats_connections_max_open",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The total number of connections waited for",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(go_sql_stats_connections_waited_for[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The total number of connections closed due to SetConnMaxIdleTime.",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "increase(go_sql_stats_connections_closed_max_idle_time[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The total number of connections closed due to SetMaxIdleConns.",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "increase(go_sql_stats_connections_closed_max_idle[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection idle",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_sql_stats_connections_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection in use",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_sql_stats_connections_in_use",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting time for a connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(go_sql_stats_connections_blocked_seconds[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The total number of connections closed due to SetConnMaxLifetime.",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "increase(go_sql_stats_connections_closed_max_lifetime[15s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "total request by url",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(mission_observability_requests_total[15s])) by (method, url)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic - Req/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(mission_observability_requests_total[15s])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic - Req/s by handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(mission_observability_requests_total[15s])) by (method, url)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ method }} {{url}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors - % (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(mission_observability_requests_total{code=~\"5..\"}[15s])) by (url)/sum(rate(mission_observability_requests_total[15s])) by (url)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ method }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latêncy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency - General",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(mission_observability_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", handler=~\"$handler\"}[15s])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(mission_observability_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", handler=~\"$handler\"}[5m])))",
     "legendFormat": "{{ job }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(mission_observability_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", handler=~\"$handler\"}[5m])))",
     "legendFormat": "{{ job }} - p99"
    }
   ]
  }
 ]
}